export const E_MISSING_API_KEY = 'E_MISSING_API_KEY'
export const E_INVALID_API_KEY = 'E_INVALID_API_KEY'
export const E_NO_RESPONSE_BODY = 'E_NO_RESPONSE_BODY'
export const E_SONNET_DOES_NOT_SUPPORT_IMAGE_UPLOAD = 'E_SONNET_DOES_NOT_SUPPORT_IMAGE_UPLOAD'
